name: GO build

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    name: Run build
    steps:
      - uses: actions/checkout@v4
      - name: Setup PSE
        uses: invisirisk/pse-action@latest
        with:
          api_url: "https://app.dev.invisirisk.com"
          app_token: ${{ secrets.IR_API_KEY_L_DEV }}

      - name: Cache Go modules, tools, and build cache
        uses: actions/cache@v4
        with:
          path: |
            ~/go/pkg/mod        # downloaded Go modules
            ~/go/bin            # installed Go tool binaries
            ~/.cache/go-build   # compiled package build cache
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      
      - name: Install dependencies
        #run: go mod tidy
        run: go mod download
        
      - name: Cleanup PSE
        if: always()
        uses: invisirisk/pse-action@latest
        with:
          cleanup: "true"
          
  gather_analytics:
     runs-on: ubuntu-latest
     name: Gather Analytics
     needs: test
     if: always()
     steps:
     - name: Gather Status
       uses: invisirisk/pse-action@latest
       with:
        api_url: "https://app.dev.invisirisk.com"
        app_token: ${{ secrets.IR_API_KEY_L_DEV }}
        send_job_status: "true"
        debug: "true"
